version: '3.9'

networks:
  gateway:
      external: true

services:
  nginx:
    image: nginx:latest
    networks:
      - gateway
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx:/root/nginx
    entrypoint: /root/nginx/entrypoint.sh
    depends_on:
      - link
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost"]
      timeout: 5s
      interval: 1s
